/**
 * Issue #883 — the machine-reviewable verb inventory.
 *
 * The issue asked for an inventory that maps every supported verb to its MCP
 * tool, the permission that gates it, its risk tier and its approval mode —
 * as a document a reviewer can diff. This module renders that document from
 * the capability registry (./registry.ts), which is the single source of
 * truth CI enforces (./registry.test.ts): add a verb without registering it
 * and the parity tests fail before the inventory can drift.
 *
 * `docs/mcp/verb-inventory.md` is GENERATED by `buildMcpVerbInventory()`.
 * It is committed because reviewers read markdown, not test output. The
 * registry test fails when the committed file diverges; regenerate it with
 * `npx tsx scripts/write-mcp-verb-inventory.mts` and review the diff as part
 * of the PR that changed the registry.
 */
import { AI_ACTION_PERMISSION_MAP, AI_TOOL_PERMISSION_MAP } from "../ai-capabilities";
import type { ActionType } from "../ai";
import { MCP_READ_REGISTRY, MCP_WRITE_REGISTRY, type McpRegistryEntry } from "./registry";
import { mcpWriteTools } from "./tools";

const REPO_DOC_PATH = "docs/mcp/verb-inventory.md";

function readRows(): string[] {
  return MCP_READ_REGISTRY.map((entry) => {
    const permission = AI_TOOL_PERMISSION_MAP[entry.name as keyof typeof AI_TOOL_PERMISSION_MAP] ?? "(unmapped)";
    const moduleTag = entry.module ? ` (${entry.module} businesses only)` : "";
    return (
      `| \`${entry.name}\` | ${entry.app} | ${entry.branchPolicy}${moduleTag} | \`${permission}\` |` +
      ` registry.test.ts, tools.test.ts, integration/mcp-connector.integration.test.ts |`
    );
  });
}

function writeRows(): string[] {
  const writeToolByAction = new Map<string, string>(
    mcpWriteTools()
      .filter((tool) => tool.binding.kind === "write")
      .map((tool) => [tool.binding.kind === "write" ? tool.binding.actionType : "", tool.descriptor.name] as const)
      .filter(([actionType]) => actionType !== ""),
  );
  return MCP_WRITE_REGISTRY.map((entry) => {
    const permission = AI_ACTION_PERMISSION_MAP[entry.actionType as ActionType] ?? "(unmapped)";
    const toolName = writeToolByAction.get(entry.actionType) ?? "(unsigned)";
    const approval =
      entry.approval === "always_approve"
        ? "always approval queue (step-up)"
        : "connection write_mode";
    return (
      `| \`${toolName}\` | \`${entry.actionType}\` | ${entry.app} | ${entry.risk} | ${approval} |` +
      ` \`${permission}\` | registry.test.ts, tools.test.ts, integration/mcp-grants-hardening.integration.test.ts |`
    );
  });
}

/** Renders the full markdown that `docs/mcp/verb-inventory.md` must equal. */
export function buildMcpVerbInventory(): string {
  const readCount = MCP_READ_REGISTRY.length;
  const writeCount = MCP_WRITE_REGISTRY.length;
  const entries: McpRegistryEntry[] = [...MCP_READ_REGISTRY, ...MCP_WRITE_REGISTRY];
  const businessWide = entries.filter(
    (entry) => entry.kind === "read" && entry.branchPolicy === "business_wide",
  ).length;
  const highRisk = entries.filter((entry) => entry.kind === "write" && entry.risk === "high").length;

  return `# Issue #883 — MCP verb inventory (machine-reviewable)

> GENERATED FILE — do not edit by hand. Source of truth: \`src/lib/mcp/registry.ts\`.
> Regenerate with \`npx tsx scripts/write-mcp-verb-inventory.mts\` after changing
> the registry; the registry test fails while this file and the registry drift.

Current surface: **${readCount} read verbs** (**${businessWide}** business-wide aggregates —
visible only to connections consented for every branch) and **${writeCount} write verbs**
(**${highRisk}** high-risk, forced through the approval queue even on \`apply\`-mode connections).

## Read verbs (what \`tools/list\` may expose subject to grants ∩ permissions)

| MCP tool | app bucket | branch policy | gating permission | enforced by tests |
|---|---|---|---|---|
${readRows().join("\n")}

## Write verbs

| MCP tool | actionType | app bucket | risk | approval mode | gating permission | enforced by tests |
|---|---|---|---|---|---|---|
${writeRows().join("\n")}

## Deliberate exclusions (not MCP verbs here by design)

- **Coworker-only actions** (\`ACTION_CATALOG[*].coworkerOnly === true\`) purposefully stay off
  the connector surface; cURL-only tooling is not part of the OAuth/MCP contract.
- **Reads excluded from the dashboard scope** in \`ai.ts\` — they never become MCP tools.
- **The platform Superadmin realm** (\`pospmcp_\`) has its own inventory in
  \`src/lib/mcp/platform-mcp.ts\`'s \`PLATFORM_MCP_NPC_TOOL_REGISTRY\` (six tools, each gated by
  a per-tool \`platformCan\` capability re-checked on every call); it is a separate bearer
  family on a separate endpoint and deliberately never appears in this document.
- **\`get_write_status\`** — the always-available introspection route for a connection's own
  execution and consent state; not a domain verb (see \`mcp/consent\` and tools tests).

## How a new verb lands here

1. Register it in \`src/lib/mcp/registry.ts\` with app bucket, branch policy, and (writes)
   risk tier + approval mode.
2. The parity tests in \`src/lib/mcp/registry.test.ts\` fail until \`${REPO_DOC_PATH}\`
   matches \`buildMcpVerbInventory()\` again — regenerate, review the diff, commit.
`;
}
